---
title: GTFOBins

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  gtfobins:
    output: true

defaults:
  - scope:
      path: '_gtfobins'
    values:
      layout: bin
